### ISSUE TITLE
Optimize is killing wordpress ajax requests

### ISSUE THREAD

**Issue by ghost** [3runoDesign/setRobot#42]
The file located under `inc/optimize.php` in some hosts kill WordPress ajax requests, like digital ocean, disabling it fixes the problem.

**Comment by 3runoDesign** [comment]
As a matter of fact, it is only the `wp_html_compression_start()` that has a problem.

**Comment by 3runoDesign** [comment]
Estou pensando seriamente em tirar essa opção. 🤔

**Comment by ghost** [comment]
Tentar reproduzir o erro seria uma boa escolha em várias versões do php.

**Comment by 3runoDesign** [comment]
>= 5.6.4
