### ISSUE TITLE
Menu burguer issue

### ISSUE THREAD

**Issue by ghost** [3runoDesign/setRobot#49]
![screenshot 2017-05-31 11 07 56](https://cloud.githubusercontent.com/assets/8512862/26635874/740ffc0a-45f1-11e7-968b-4cf04c8671ee.png)

Bower version: 1.8.0
Node.js version: v7.7.1
npm version: 4.1.2

Platform: macOS Sierra
version: 10.12.5

**Comment by 3runoDesign** [comment]
Everything is normal. Make sure you're importing bourbon.

**Comment by 3runoDesign** [comment]
@gabriellacerda ^

**Comment by ghost** [comment]
'-' shure!
