### ISSUE TITLE
Plugin para editor de código

### ISSUE THREAD

**Issue by ghost** [3runoDesign/setRobot#55]
É bem divertido utilizar o setRobot, só que muitas vezes você não sabe de cabeça as funções, e seria legal se fosse possível apenas com alguns atalhos fazer uso dessas funções. @lucasprogamer @3runoDesign

**Comment by 3runoDesign** [comment]
Pra isso é interessante documentar e com o amadurecimento dele fica mais fácil.

**Comment by 3runoDesign** [comment]
aceitando PR @gabriellacerda

**Comment by lucasprogamer** [comment]
@gabriellacerda  Acho que Atalhos não resolveria isso o certo mesmo é documentar

**Comment by ghost** [comment]
Ambos fazem parte da flow do desenvolvedor que utiliza setRobot, o plugin seria uma extensão dessa documentação, feature adicionada para a nova versão.

**Comment by ghost** [comment]
@3runoDesign @lucasprogamer na opinião de vocês, o melhor seria escrever a sentença de forma normal ou utilizando o @ e então ele é substituído pela função do setRobot?

**Comment by lucasprogamer** [comment]
Sentença normal, pq na do blade ele sempre duplica o @

**Comment by ghost** [comment]
Ok

**Comment by ghost** [comment]
https://github.com/gabriellacerda/setRobot-bundle
