### ISSUE TITLE
Add ES6

### ISSUE THREAD

**Issue by 3runoDesign** [3runoDesign/setRobot#57]
- [x] [Optimizing Performance](https://facebook.github.io/react/docs/optimizing-performance.html#use-the-production-build) - Add `process.env.NODE_ENV = 'production';` on `tasks/build.js`
- [x] Add `.babelrc`

**Comment by 3runoDesign** [comment]
@gabriellacerda e @lucasprogamer deem uma olhada na branch que fiz https://github.com/3runoDesign/setRobot/tree/add-es6

**Comment by 3runoDesign** [comment]
Acho que agora falta pouco.

**Comment by 3runoDesign** [comment]
https://github.com/3runoDesign/setRobot/pull/60

**Comment by lucasprogamer** [comment]
eita
