### ISSUE TITLE
Create the page soon

### ISSUE THREAD

**Issue by 3runoDesign** [3runoDesign/setRobot#64]

**Comment by 3runoDesign** [comment]
Alguma novidade @lucasprogamer

**Comment by lucasprogamer** [comment]
A partir de hoje já consigo mexer

**Comment by lucasprogamer** [comment]
@3runoDesign Eu fiz lá da uma olhada no #68

**Comment by 3runoDesign** [comment]
@lucasprogamer depois colocar no README na https://github.com/3runoDesign/setRobot#theme-structure
