### ISSUE TITLE
Bower guide added to wiki

### ISSUE THREAD

**Issue by ghost** [3runoDesign/setRobot#65]
Agora a wiki conta com detalhes de como gerenciar pacotes que já vem inclusos com o setRobot, e como adicionar novos.

**Comment by 3runoDesign** [comment]
Caso queira realmente remover o **Bourbon,** é preciso alterar o [`includesPath`](https://github.com/3runoDesign/setRobot/blob/master/gulpTasks/config/styles.js#L15), remover as pastas: [helper](https://github.com/3runoDesign/setRobot/tree/master/resources/assets/sass/helper) e [base](https://github.com/3runoDesign/setRobot/tree/master/resources/assets/sass/base), já que requerem o mesmo.

Tanto o **Bourbon** e o **family.scss**, são um aglomerado de Mixins e Helpers para SASS, não vejo onde eles possam atrapalhar a utilização de FW de qualquer natureza seja bootstrap ou foundation. 

Acho que não é necessário remover o **bourbon** e/ou **family.scss**, pois ambos frameworks são para ajudar no desenvolvimento tedioso do dia-a-dia e realmente o intuito do **setRobot** nunca foi de style pronto.

**Comment by 3runoDesign** [comment]
Removendo o **bourbon** é necessário remover a pasta `sass/helper` e `sass/base` já que os arquivos utilizam ele.

O intuito do **setRobot** nunca foi ter um estilo padrão, porém ter meios de agilizar o desenvolvimento de styles e scripts.

A utilização do bourbon, family.scss, `sass/helper` e `sass/base` não irá interferir na escolha de qualquer outro framework de css como bootstrap, foundation e outros.

**Comment by 3runoDesign** [comment]
https://github.com/3runoDesign/setRobot/issues/66

**Comment by 3runoDesign** [comment]
https://github.com/3runoDesign/setRobot/issues/66
