### ISSUE TITLE
Version ripping

### ISSUE THREAD

**Issue by 3runoDesign** [3runoDesign/setRobot#66]
Depois de conversar com o @gabriellacerda sobre algumas dúvidas sobre esse projeto resolvi criar esse issue para que possamos nos organizar definitivamente o que precisa melhorado para liberar a versão.

### Etapa 4: Documentação
- [ ] Introdução (saudações, sobre, motivos e etc)
- [ ] Instalação
- [ ] Pré-requisitos
- [ ] Comandos (Gulp)
- [ ] Pacotes front-end (Bower)
- [ ] Estrutura de arquivos/diretórios
- [ ] Libraries
- [ ] Helpers

**Comment by 3runoDesign** [comment]
Sobre a etapa 3, seria separar responsabilidades que não são do tema. Blade, Containers e afins

**Comment by lucasprogamer** [comment]
Acho que cabe um espaço para samples.

**Comment by 3runoDesign** [comment]
Na documentação? Pensando em criar um tuts de HTML para Wordpress usando **setRobot**

**Comment by lucasprogamer** [comment]
sim exatamente isso. como eu disse antes um espaço pra cases de sucesso tbm fica daora
