### ISSUE TITLE
RFC #1: Custom Signup screen

### ISSUE THREAD

**Issue by appsdest** [3runoDesign/setRobot#67]
setRobot is being a nice starter kit to our team, the new login screen is amazing, but setRoboters where is the custom signup screen?

**Comment by ghost** [comment]
@3runoDesign

**Comment by 3runoDesign** [comment]
I'm working on it. @appsdest

**Comment by appsdest** [comment]
sure ^^

**Comment by gabriellacerda** [comment]
Hey apps dest, do the harley shake

**Comment by appsdest** [comment]
Do do do do, do do do do do do dooooo, do do do do

It's like this @gabriellacerda and @3runoDesign isn't it?

**Comment by appsdest** [comment]
I think I'm the same

**Comment by gabriellacerda** [comment]
guy

**Comment by lucasprogamer** [comment]
setRoboters, i like that :D
