### ISSUE TITLE
Condições da pág. de manutenção

### ISSUE THREAD

**Issue by 3runoDesign** [3runoDesign/setRobot#70]
Verificar se a página de manutenção expirou ou está desabilitada. Hoje se eu desabilitar ela continua redirecionando para a pág. de manutenção.

**Comment by 3runoDesign** [comment]
usar algo como `get_option()` certificando que as opções esteja habilitadas

**Comment by lucasprogamer** [comment]
Queria mesmo era fazer sem redirencionar :/
o Jeito que eu consegui foi fazendo um include do template, mas ele acaba não usando o blade nem as funções.

**Comment by 3runoDesign** [comment]
vamos fazer uma call pra olhar isso
